# Course Resources

## Packet, Recommended Texts, and Website

*Course Packet (Digital)* There is a no-cost digital course packet that is accessible through the course Canvas site. These materials will also be printed and distributed in class when necessary for use. All distributed course materials will come three hole punched so it is **recommended that you maintain a three-ring binder for this course**.

*Textbook (Recommended Only)* No textbook is required for this course. However, if you need a reference or if you are planning on continuing your work with and study of soils in the future, I recommend the text, which is available from most online booksellers. There are two versions of the recommended text, and many editions. The full version (more than 1,000 pages) is called [The Nature and Properties of Soils](https://www.amazon.com/Nature-Properties-Soils-Ray-Weil/dp/9356062714/ref=pd_lpo_1?pd_rd_w=RiBr5&content-id=amzn1.sym.116f529c-aa4d-4763-b2b6-4d614ec7dc00&pf_rd_p=116f529c-aa4d-4763-b2b6-4d614ec7dc00&pf_rd_r=D8TS19HCDQ6X5VVA400V&pd_rd_wg=RC7HE&pd_rd_r=50c60f58-2d69-4008-987b-87e3904f83a1&pd_rd_i=9356062714&psc=1) by Ray Weil and Nyle Brady and is on its 15th Edition (2016 for hardcover/2022 for paperback). The abridged version is called [Elements of the Nature and Properties of Soils](https://www.amazon.com/Elements-Nature-Properties-Soils-4th/dp/0133254593) also by Ray Weil and Nyle Brady and is on its 4th Edition (2018). Note that the 15th edition of the full text and the 4th edition of the abridged text are the newest, but the previous 14th (full version) and 3rd (abridged version) editions work just as well and are generally much cheaper to purchase from online book sellers. The course schedule has recommended readings from the 4th edition of Elements of the Nature and Properties of Soils or the 14th Edition (paperback) of The Nature and Properties of Soils:

-   Elements of the Nature and Properties of Soils (4th Ed.), Brady and Weil

OR

-   The Nature and Properties of Soils (15th Ed.), Brady and Weil

*Course Website:* Lecture notes and other course materials will be available on the class website through Canvas. If you are registered for the class, you have automatically been given access privileges to the Soil 2125 Canvas site.

::: callout-tip
## Canvas Access

-   Via myU portal: Go to myU Portal page at <http://myu.umn.edu>, login with your Internet ID, and click on the Key Links tab. Click on Canvas in the dropdown menu.

-   Via Canvas server: Go to <http://canvas.umn.edu> and login there with your Internet ID. Once logged in, you will be able to see the link to sites you have access to.
:::

## Other Resources

Minnesota Board of Water and Soil Resources (BWSR) [Wetland Delineation Guidance and Resources](https://bwsr.state.mn.us/delineation-guidance-resources)

Minnesota Board of Water and Soil Resources (BWSR) [Wetland Functional Assessment](https://bwsr.state.mn.us/wetland-functional-assessment)

Minnesota Board of Water and Soil Resources (BWSR) [Delineation Manuals](https://bwsr.state.mn.us/delineation-manuals)

Minnesota Board of Water and Soil Resources (BWSR) [Hydrology and Antecedent Precipitation](Minnesota Board of Water and Soil Resources (BWSR) [Delineation Manuals](https://bwsr.state.mn.us/delineation-manuals)

Minnesota Department of Transportation Project Development: [Wetlands Process](https://www.dot.state.mn.us/project-development/subject-guidance/wetlands/process.html)

Minnesota Department of Natural Resources State Climatology Office: [Wetland Delineation Precipitation Data Retrieval from a Gridded Database](https://climateapps.dnr.state.mn.us/gridded_data/precip/wetland/wetland.asp)

US Army Corps of Engineers (USACE) [Wetland Delineation Manual and Regional Supplements](https://www.usace.army.mil/Missions/Civil-Works/Regulatory-Program-and-Permits/reg_supp/)





## Recommended Habits for Success in this Class

Regular participation is key in this course! We have designed the syllabus and schedule so that there is a regular "rhythm" to every week of the class. During a typical week, you will have a **Pre-Discussion Quiz** due on Canvas by Wednesday at 11:59PM, a live discussion session in 174 Plant Growth Facilities on Thursdays, and a **Weekly Summary Quiz** due by Friday at 11:59PM. 

You will complete the lab at a time of your choosing between Wednesday and Friday each week. You'll sign up for a lab timeslot during the first week of class. We hope that this helps structure your schedule and your interaction with the asynchronous lecture materials. 

Course materials will be posted at least one week in advance, so you are free to work on a schedule that works best for you. If you engage with all of the lecture and lecture companion materials, attend discussion sections and lab at your chosen time, you will be very familiar with the material and should be successful in the class. 

Come to discussion prepared to participate! Unit summaries, zoom sessions, and additional materials on the Canvas site will provide you with the tools for success. We really look forward to meeting and working with you. 

**You are encouraged to ask any and all questions - even the "stupid" ones! (P.S. There are no stupid questions ;).**
