# Field Sessions

## What to Expect!

- The weather may vary dramatically when we are in the field. We will plan to work through the heat, rain and cold, so dress accordingly.

- Mosquitos or black flies may be present at times during our September field sessions. If you think this may be an issue for you, consider bringing repellant and/or a bug net to wear over your head. 

- During your group work in October/November it may be cold at times. Please dress accordingly.

## Clothing and footwear.

- Wear PANTS for all field sessions! Leggings probably not a good choice most days.

- Wear close-toed shoes or boots (bring rubber boots if you have them). I do have some extra rubber boots that can be loaned out or borrowed.

- Your feet can get wet and you will be just fine for a day. Just allow your feet to dry out at night! 

- If your rain gear is semi-waterproof/semi-breathable, consider a cheap poncho in case we have a super rainy day.

## Food and Water

- Because our field sessions will be later in the afternoon and may go until 6:00pm, please bring food and or snacks with you if you feel you will need it at that time of day.

- Bring at least one bottle of water each day we are in the field, two if you feel your consumption may be high or if it is hot (most likely in September). Average requirement depends on temperature and person, we shouldn’t see anything more than 85 degree WBGT, and easy work so you can estimate a max of 2 liters per session.

## Ticks.

Ticks may be out and active through October, however they tend to be most prevalent in dry to mesic sites, and less prevalent/absent from wetlands. Ticks “quest”, and they grab on to your pant legs. They crawl up until they find a tight place – this is where they usually stop. They do not drop from trees.

- Ticks can carry human pathogens, prevalence is low, but important (Staph/Lymes).

- Deer ticks are much more likely to transmit than wood ticks.

- Ticks need 24-36 hours after biting to transmit Lyme, so doing a good nightly tick check after a field day is important.

- Deet and permethrin applied to key areas/clothing items can also mitigate risk.