# The Fine Print

::: callout-important
## Key Summary - Most of the below text and policies can be summed up with the following points:

-   Take responsibility for your own actions.
-   Be honest.
-   Respect yourself and everyone else! Zero tolerance for discrimination or harassment of any kind.
-   Don't do things in class that aren't related to class
-   If you need help of any kind, just ask!
:::

## Attendance Policy

Legitimate discussion absences must be arranged in advance in order to receive full points for make-up work. Make-up work policies for unexcused absences are described in detail in @sec-unexcusedabsences. I am also more than willing to work with you for legitimate excuses as described in @sec-absences.

## Student Conduct Code {#sec-conductcode}

The University seeks an environment that promotes academic achievement and integrity, that is protective of free inquiry, and that serves the educational mission of the University. Similarly, the University seeks a community that is free from violence, threats, and intimidation; that is respectful of the rights, opportunities, and welfare of students, faculty, staff, and guests of the University; and that does not threaten the physical or mental health or safety of members of the University community. You are expected to be familiar with and adhere to the [Board of Regents Policy: Student Conduct Code](https://regents.umn.edu/sites/regents.umn.edu/files/2022-07/policy_student_conduct_code.pdf).

## Use of Personal Electronic Devices

Both lecture and discussion are designed to be active, technology-assisted environments. To that end, the use of personal electronics such as cell phones, tablets or laptops are encouraged if they are used for class purposes. The use of any electronic music players is prohibited unless prior approval has been granted by the instructor, and the use of the prior listed devices is prohibited if used for purposes other than class.

## Sexual Harassment, Sexual Assualt, and Relationship Violence

*Sexual harassment* means unwelcome sexual advances, requests for sexual favors, and/or other verbal or physical conduct of a sexual nature. Such conduct has the purpose or effect of unreasonably interfering with an individual's work or academic performance or creating an intimidating, hostile, or offensive working or academic environment in any University activity or program. Such behavior is not acceptable in the University setting. The University of Minnesota is committed to taking prompt and effective steps intended to end sexual harassment, sexual assault, stalking, relationship violence, and related retaliation, prevent their recurrence and, as appropriate, remedy their effects as outlined in both the [University of Minnesota Sexual Harassment, Sexual Assault, Stalking and Relationship Violence Policy](https://policy.umn.edu/hr/sexharassassault) and the [Board of Regents Sexual Harassment, Sexual Assualt and Relationship Violence Policy](https://regents.umn.edu/sites/regents.umn.edu/files/2020-08/policy_sexual_harassment_sexual_assault_stalking_and_relationship_violence.pdf).

## Equity, Diversity, Equal Opportunity, and Affirmative Action

As an instructor, I am committed to creating a learning environment where everyone feels safe, honored, and respected.

The Department of Soil, Water, and Climate (SWAC), *of which our teaching team is a part*, includes faculty, staff, and students who are committed to understanding the earth, environment, and atmosphere and how we interact with our world. We are an interdisciplinary group; we take pride in the fact that our backgrounds and perspectives vary. We embrace the diverse experiences of individuals, communities, cultures, and nations and understand that those experiences enrich and inform our department. We recognize that science and culture are inseparable and are both crucial parts of our work. 

The University provides equal access to and opportunity in its programs and facilities, without regard to race, color, creed, religion, national origin, gender, age, marital status, disability, public assistance status, veteran status, sexual orientation, gender identity, or gender expression in accordance with the [Board of Regents Equity, Diversity, Equal Opportunity, and Affirmative Action Policy](https://regents.umn.edu/sites/regents.umn.edu/files/2019-09/policy_equity_diversity_equal_opportunity_and_affirmative_action.pdf).

## Disability Accomodations

The University of Minnesota is committed to providing equitable access to learning opportunities for all students. The [Disability Resource Center](https://disability.umn.edu) is the campus office that collaborates with students who have disabilities in any form to provide and/or arrange reasonable accommodations. If you have, or think you may have, a disability (e.g., mental health, attention, learning, chronic health, sensory, or physical), please contact DRC at 612-626-1333 to arrange a confidential discussion regarding equitable access and reasonable accommodations. If you are registered with DRC and have a current letter requesting reasonable accommodations, please contact your instructor as early in the semester as possible to discuss how the accommodations will be applied in the course.

## Animals

Animals are not permitted in class unless they are certified service animals or emotional support animals approved through the [Disability Resource Center](https://disability.umn.edu).

## Mental Health and Stress Management

As a student you may experience a range of issues that can cause barriers to learning, such as strained relationships, increased anxiety, alcohol/drug problems, feeling down, difficulty concentrating and/or lack of motivation. These mental health concerns or stressful events may lead to diminished academic performance and may reduce your ability to participate in daily activities. University of Minnesota services are available to assist you. In addition to campus-wide [mental health resources](https://safe-campus.umn.edu/mental-health), the [CFANS Wellness Navigator, Rose Simon](https://cfans.umn.edu/academics/academic-advisors/rose-simon), is available to meet the needs of students as it relates to personal well-being for any reason. If you are interested in meeting with Rose, her webpage shares a bit more about the ways that you can [get connected](https://cfans.umn.edu/academics/wellbeing).

## Academic Freedom and Responsibility

Academic freedom is a cornerstone of the University. Within the scope and content of the course as defined by the instructor, it includes the freedom to discuss relevant matters in the classroom. Along with this freedom comes responsibility. Students are encouraged to develop the capacity for critical judgment and to engage in a sustained and independent search for truth. Students are free to take reasoned exception to the views offered in any course of study and to reserve judgment about matters of opinion, but they are responsible for learning the content of any course of study for which they are enrolled. Reports of concerns about academic freedom are taken seriously, and there are individuals and offices available for help. Contact [the instructor](https://swac.umn.edu/people/nic-jelinski), the [Department Head](https://swac.umn.edu/people/brent-williams), your [academic advisor](https://cfans.umn.edu/academics/undergrad-resources/academic-advisors), the [CFANS Associate Dean for Academic Programs and Faculty Affairs](https://apec.umn.edu/people/frances-homans), or the [Vice Provost for Faculty and Academic Affairs](https://faculty.umn.edu/about-us/staff-directory) in the Office of the Provost.

## Appropriate Student Use of Class Notes and Course Materials

Taking notes is a means of recording information but more importantly of personally absorbing and integrating the educational experience. However, broadly disseminating class notes beyond the classroom community or accepting compensation for taking and distributing classroom notes undermines instructor interests in their intellectual work product while not substantially furthering instructor and student interests in effective learning. Such actions violate shared norms and standards of the academic community.

## Scholastic Dishonesty

You are expected to do your own academic work and cite sources as necessary. Failing to do so is scholastic dishonesty. Scholastic dishonesty means plagiarizing; cheating on assignments or examinations; engaging in unauthorized collaboration on academic work; taking, acquiring, or using test materials without faculty permission; submitting false or incomplete records of academic achievement; acting alone or in cooperation with another to falsify records or to obtain dishonestly grades, honors, awards, or professional endorsement; altering, forging, or misusing a University academic record; or fabricating or falsifying data, research procedures, or data analysis. (see Student Conduct Code @sec-conductcode). If it is determined that a student has cheated, he or she may be given an "F" or an "N" for the course, and may face [additional sanctions](https://communitystandards.umn.edu/scholastic-dishonesty-sanctioning-guidelines) from the University.

The Office for Community Standards provides a wealth of information on the Student Conduct Code and [Scholastic Dishonesty](https://communitystandards.umn.edu/report-incidents/reporting-scholastic-dishonesty). If you have additional questions, please clarify with your instructor for the course. Your instructor can respond to your specific questions regarding what would constitute scholastic dishonesty in the context of a particular class-e.g., whether collaboration on assignments is permitted, requirements and methods for citing sources, if electronic aids are permitted or prohibited during an exam.

## Acknowledging Extraordinary Times

We continue to live in extraordinary times that may challenge all of us in unexpected ways. Experiencing stress and anxiety during these times is normal, and while we cannot pretend to understand the wide range of challenges that each of you may be experiencing, know that we are here to support you as best we can. Please communicate with us early and often if you anticipate major barriers to your learning in this class, particularly if you are a student with increased caregiving responsibilities for children or other family members.

## Financial Support

If you are in need of emergency financial support, the University has an [emergency funds program](https://onestop.umn.edu/finances/types-financial-aid/student-emergency-funds) which allows you to request funds with a typical range of \$50-\$1,000.
