# Further Opportunities in Soil Science

## Courses and Certifications

*Soil Science Minor and Professional Certifications:* The Department of Soil, Water and Climate hosts a 20 credit minor in Soil Science which can be added on to most majors. Classes in this minor can also prepare you to meet the requirements for the Professional Soil Scientist certification exam and prepare you to receive professional certifications in Wetland Delineation, On-site Sewage Treatment and Erosion Control. Nic is the minor coordinator: jeli0026\@umn.edu.

*Field Classes:* If you want to be in the field and see more soils in person, consider taking SOIL 4511 (Field Study of Soils - 2cr./May Session) and SOIL 3521 (Soil Judging - 1cr./Fall). Contact Nic directly if you are interested!

## Careers
There are many opportunities for engaging in careers related to soil science. Soil science and soil science adjacent careers are available throughout the public, private and non-profit sectors. I will be sending out career and internship opportunities throughout the semester.
