# Absences and Makeup Policies

## Excused Absences {#sec-absences}

[University policy](https://policy.umn.edu/education/makeupwork) recognizes that there are a variety of legitimate circumstances in which students will miss coursework, and that accommodations for makeup work will be made. These situations generally fall into several categories:

-   illness, physical or mental, of the student or a student's dependent;
-   medical conditions related to pregnancy;
-   participation in intercollegiate athletic events;
-   subpoenas;
-   jury duty;
-   military service;
-   bereavement, including travel related to bereavement;
-   religious observances;
-   participation in formal University system governance, including the University Senate, Student Senate, and Board of Regents meetings, by students selected as representatives to those bodies;
-   taking college entrance exams (PSAT, ACT, SAT) for Post-Secondary Enrollment Option (PSEO) students that are provided at their high school; and
-   activities sponsored by the University if identified by the senior academic officer for the campus or the officer's designee as the basis for excused absences.

These absences should be pre-coordinated with the instructor as soon as they are known - in emergency or unexpected situation, communication may occur after the fact. **All other absences are considered unexcused absences**

## Makeup Policies for Unexcused Absences {#sec-unexcusedabsences}

*Pre-Discussion Quiz:* If you miss a pre-discussion quiz you will receive a 2 pt deduction. You can still make up the quiz for 3/5 pts, however, as long as it is turned in to Canvas by 11:59PM on Wednesday of the following week to receive these makeup points. If you do not complete your make-up within 1 week of the original due date, you will receive a 0 for the assignment for any unexcused absences.

*Weekly Summary Quiz* If you miss the weekly summary quiz you will receive a 2 pt deduction. You can still complete the quiz for 13/15 pts, however! Your weekly summary quiz must be turned in by 11:59PM on Friday of the following week to receive these makeup points. If you do not complete your make-up within 1 week of the original due date, you will receive a 0 for the assignment for any unexcused absences.

*Discussion Collaborative Exercises:* Discussion exercises are team activities. If you miss discussion you will receive a 2 pt deduction. You can still complete the exercise for 4/6 pts, however. Your completed exercise must be turned in by the beginning of discussion the following week to receive a grade. If you do not complete your make-up within 1 week, you will receive a 0 for the assignment for any unexcused absences.

*Soil Property and Land Use Reports:* Deduct 10% for every 24 hour period late for any unexcused delays.
